### ISSUE TITLE
testing on non dataset images

### ISSUE THREAD

**Issue by ak9250** [anmolmann/GANimation-Replication#1]
can you test on your own images outside the datasets?

**Comment by anmolmann** [comment]
I have tested it with a few images outside the dataset. But I didn't store the results. I will test it once again and post the results soon. But I must mention, there were many failing instances as well.

**Comment by ttbro** [comment]
@anmolmann 
hi, thanks for the work!
I just wonder how do you get the AU value?  as you mentioned before using the openface tools, 
However  I just the got the different AU value from Openface on the same image,
would you please give the exact detail about the progress of AU?

**Comment by anmolmann** [comment]
Yes, I did use Openface for just some of the dataset. But I got the good dataset (EmotioNet) along with AU values.

**Comment by xrtbuaa** [comment]
@anmolmann 
ok, thanks

**Comment by anmolmann** [comment]
@xrtbuaa The link is actually given in the original GANimation https://github.com/albertpumarola/GANimation/ implementation.
